[2024-06-06T15:44:44.036+0000] {processor.py:161} INFO - Started process (PID=3593) to work on /opt/airflow/dags/path1.py
[2024-06-06T15:44:44.037+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/path1.py for tasks to queue
[2024-06-06T15:44:44.038+0000] {logging_mixin.py:188} INFO - [2024-06-06T15:44:44.038+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/path1.py
[2024-06-06T15:44:44.236+0000] {logging_mixin.py:188} INFO - [2024-06-06T15:44:44.235+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/path1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/path1.py", line 34, in <module>
    aws_access_key_id=aws_access_key_id,
NameError: name 'aws_access_key_id' is not defined
[2024-06-06T15:44:44.236+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/path1.py
[2024-06-06T15:44:44.243+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/path1.py took 0.211 seconds
